### ISSUE TITLE
Nullscape Compatibility

### ISSUE THREAD

**Issue by Fyoncle** [The-Architects727/BiggerEndCities#9]
![image](https://github.com/The-Architects727/BiggerEndCities/assets/63975256/963e1163-1f25-43a4-a689-134f33bc02b6)
They spawning weirdly inside the upper islands, what can i do about this?

**Comment by The-Architects727** [comment]
Ok. This datapack only changes the look of the end cities. I am pretty sure that these same issues would be present even if you did not use my datapack. 
if you make a new world with the same seed, but without the pack and the city generates correctly, then please tell me. And I will look into it.

**Comment by The-Architects727** [comment]
What exactly are you wanting?
If you want the walkways to cut more rounded, and tunnel like holes into the islands as they grow, that it an easy fix.
If you are wanting them to just not grow into the islands, then I am afraid that that is not really possible. Simply because there is no way to check if blocks exist in a space, before placing the next piece of a structure.


what version of the BetterEndCities datapack are you using?

**Comment by Fyoncle** [comment]
Well, i think it was just vanilla behavior, same seed broken at Vanilla too
